const propertiesLegacy=[
  ['Casa Los Alerces 1450','Las Condes','Lun 13 oct','10:00','Vale Vista + formulario','María González','ATRASADO','Venció hoy a las 14:00','1600585154340-be6161a56a0c'],
  ['Depto. San Martín 588','Santiago Centro','Mar 14 oct','15:30','Emisión Vale Vista','Juan Pérez','ALERTA','Vence en 18 h','1600607687939-ce8a6c25118c'],
  ['Casa El Roble 972','Ñuñoa','Mié 15 oct','11:30','Ingreso a sala virtual','Carla Rojas','ALERTA','Vence en 45 min','1600566753190-17f0baa2a6c3'],
  ['Casa Valle Alegre 321','La Florida','Mié 15 oct','16:00','Documentación','Diego Torres','BIEN','Vence mañana','1600047509807-ba8f99d2cdde'],
  ['Depto. Parque 1234','Providencia','Jue 16 oct','10:00','Preparación remate','Andrea Silva','BIEN','Vence mañana','1600607687920-4e2a09cf159d'],
  ['Casa Mirador 777','Peñalolén','Jue 16 oct','14:30','Revisión final','Carlos Soto','BIEN','Vence mañana','1600585154526-990dced4db0d'],
  ['Terreno El Arrayán','Lo Barnechea','Vie 17 oct','12:00','Preparación de remate','Paula Díaz','BIEN','Vence en 2 días','1500382017468-9049fed747ef']
];
const properties=window.RematesData.items.map(x=>[x.title,x.place,x.date,x.time,x.stage,x.person,x.status,x.due,x.photo]);const id=Math.min(7,Math.max(1,Number(new URLSearchParams(location.search).get('id'))||1));const p=properties[id-1];const statusClass=p[6]==='ATRASADO'?'late':p[6]==='ALERTA'?'alert':'good';
mobileDetail.innerHTML=`<div class="hero"><img src="https://images.unsplash.com/photo-${p[8]}?auto=format&fit=crop&w=900&q=80" alt="${p[0]}"><span class="status ${statusClass}">${p[6]}</span></div><div class="detail-body"><h1>${p[0]}</h1><p class="location">${p[1]}</p><div class="date-line"><span>▣ ${p[2]} 2025</span><span>◷ ${p[3]}</span></div><div class="urgent"><div><b>${p[4]}</b><small>${p[7]}</small></div></div><div class="info-list"><div class="info"><span>♙</span><div><small>Responsable actual</small><b>${p[5]}</b></div></div><div class="info"><span>▤</span><div><small>Próxima acción</small><b>${p[4]}</b></div></div><div class="info"><span>▣</span><div><small>Fecha límite</small><b style="color:var(--red)">${p[7]}</b></div></div><div class="info"><span>◷</span><b>Ver historial</b><span>›</span></div></div><button class="primary" id="completeMobile">Marcar acción como completada</button><button class="action-btn" style="width:100%;margin-top:10px" onclick="location.href='hello.html'">Volver al inicio</button></div>`;completeMobile.onclick=()=>{window.RematesData.update(id,{status:'BIEN',stage:'Listo para remate',due:'Acción completada',progress:100});completeMobile.textContent='✓ Cambio guardado';completeMobile.disabled=true};
