const page=document.body.dataset.page,R=window.RematesData;let week=R.getWeek();
const labels={semana:'Calendario semanal',documentos:'Documentos',reportes:'Reportes'};
function shell(){document.getElementById('screen').innerHTML=`<div class="screen-app"><div data-side></div><main class="screen-main"><header class="screen-top"><h1>${labels[page]}</h1><div class="user"><img class="avatar" src="https://i.pravatar.cc/100?img=47"><div><strong>María González</strong>Gerente General</div></div></header><div class="screen-content" id="pageContent"></div></main><div data-mobile-nav></div></div><div class="toast" id="pageToast"></div>`;Shell.mount()}
function statusClass(s){return {ATRASADO:'late',ALERTA:'alert',SUSPENDIDO:'paused',CANCELADO:'cancelled'}[s]||'good'}
function weekBar(){return `<div class="week screen-week"><button class="sq" data-week="-1" aria-label="Semana anterior">‹</button><span>${R.weekRange(week).label}</span><button class="sq" data-week="1" aria-label="Semana siguiente">›</button></div>`}
function bindWeek(draw){document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{week=R.setWeek(week+Number(b.dataset.week));draw()})}
function renderDocs(){const items=R.weekItems(week);const docs=items.flatMap(x=>x.documents.map((d,i)=>({property:x,id:x.id,index:i,name:d[0],type:d[1],status:d[2]})));pageContent.innerHTML=`${weekBar()}<div class="screen-toolbar"><div><b>Repositorio de documentos</b><div style="color:var(--muted);font-size:13px">${docs.length} archivos vinculados</div></div><label class="search"><input id="docSearch" placeholder="Buscar documento o propiedad…"></label></div><table class="document-table"><thead><tr><th>Documento</th><th>Propiedad</th><th>Responsable</th><th>Estado</th><th></th></tr></thead><tbody id="docRows"></tbody></table>`;function rows(q=''){docRows.innerHTML=docs.filter(d=>(d.name+d.property.title).toLowerCase().includes(q.toLowerCase())).map(d=>`<tr><td><div class="doc-name"><span class="doc-icon">${d.type}</span>${d.name}</div></td><td>${d.property.title}<small style="display:block;color:var(--muted)">${d.property.place}</small></td><td>${d.property.person}</td><td><span class="status ${d.status==='APROBADO'?'good':d.status==='PENDIENTE'?'late':'alert'}">${d.status}</span></td><td><button class="action-btn" data-doc="${d.id}-${d.index}">${d.status==='PENDIENTE'?'Revisar':'Ver'}</button></td></tr>`).join('')||`<tr><td colspan="5" class="empty-state">${docs.length?'Ningún documento coincide con la búsqueda.':'No hay remates programados para esta semana.'}</td></tr>`;document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>toast('Documento abierto en modo maqueta'))}rows();docSearch.oninput=e=>rows(e.target.value);bindWeek(renderDocs)}
function toast(message){pageToast.textContent=message;pageToast.classList.add('show');setTimeout(()=>pageToast.classList.remove('show'),2200)}
shell();if(page==='documentos')renderDocs();
